name: Activation

on:
  push:
    branches: [ master, CI ]
  pull_request:
    branches: [ master ]
    
jobs:
  activation:
    name: Request Activation
    runs-on: ubuntu-latest
    steps:
      #Request for manual activation file        
      - name: Activate
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v2.0-alpha-1
        with:
          unityVersion: 2020.1.17f1
        
      #Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}