name: Game Build

on:
  push:
    branches: [ master, CI ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build TC for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - Team-Capture
        unityVersion:
          - 2020.2.1f1
        targetPlatform:
          - StandaloneWindows64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      - name: Cache for ${{ matrix.targetPlatform }}
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.projectPath }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Build Game
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: 'Team-Capture'
          buildsPath: '${{ matrix.projectPath }}/Builds'
          versioning: None