name: Game Build

on:
  push:
    branches: [ master, CI ]
  pull_request:
    branches: [ master ]

env:
  gameName: 'Team-Capture'
  version: 'v0.2-Alpha'
  blenderVersion: '2.83lts'
    
jobs:
  build:
    name: Build TC for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - Team-Capture
        unityVersion:
          - 2020.2.1f1
        targetPlatform:
          - StandaloneWindows64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      - name: Install Blender
        run: |
          sudo snap install blender --channel=${{ env.blenderVersion }}/stable --classic
          export PATH="/snap/bin:$PATH"

      - name: Cache for ${{ matrix.targetPlatform }}
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-

      - name: Build Player for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.gameName }}
          buildsPath: '${{ matrix.projectPath }}/Builds'
          versioning: Custom
          version: ${{ env.version }}
          buildMethod: Team_Capture.Editor.CIBuilder.StartVoltBuilder
      
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.gameName }}-${{ matrix.targetPlatform }}-${{ env.version }}-DevOpsBuild'
          path: '${{ matrix.projectPath }}/Builds/${{ matrix.targetPlatform }}-DevOpsBuild'